// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6SSAIoD-bQ17_UcnN_t984N3XQNJSd3Y',
    appId: '1:81200823843:web:e6288d945772166cccbb96',
    messagingSenderId: '81200823843',
    projectId: 'alu01-c17cd',
    authDomain: 'alu01-c17cd.firebaseapp.com',
    databaseURL: 'https://alu01-c17cd-default-rtdb.firebaseio.com',
    storageBucket: 'alu01-c17cd.appspot.com',
    measurementId: 'G-LE6WM6LT5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ccSgsfpZi7FzBJzgCqowpmj8ryq-eVI',
    appId: '1:81200823843:android:aa34b20d4a9a0d83ccbb96',
    messagingSenderId: '81200823843',
    projectId: 'alu01-c17cd',
    databaseURL: 'https://alu01-c17cd-default-rtdb.firebaseio.com',
    storageBucket: 'alu01-c17cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLNirhXzUdyjIxzqRmZn-MOKFgDAMAw0',
    appId: '1:81200823843:ios:84ab9b3494c7877fccbb96',
    messagingSenderId: '81200823843',
    projectId: 'alu01-c17cd',
    databaseURL: 'https://alu01-c17cd-default-rtdb.firebaseio.com',
    storageBucket: 'alu01-c17cd.appspot.com',
    iosBundleId: 'com.example.fiv',
  );
}
